### ISSUE TITLE
Won't work(internet required on installation)

### ISSUE THREAD

**Issue by megabob1985** [Vegz78/McAirpos#36]
I opened a console on Recalbox as you said, but when I put in the code, nothing happened. I might be doing something wrong since this is my first time doing anything like this, but your instructions are so unclear, I need pictures or a  video, please. I really need to figure out how this works. @rdmueller @Vegz78

**Comment by Vegz78** [comment]
Hi and thanks for trying McAirpos!

Sorry it is not working for you, and for the instructions which probably could be better, ref. for instance @rdmueller’s most recent pull request regarding the same. However, we did a lot of work together on McAirpos before and during Christmas, and I’ve been feeling a bit sated since.

But maybe I could help you here instead?

What version of Recalbox are you running and exactly which commands/code did you enter in the console? Did you get any error messages? -And was the Recalbox console connected to internet, by the way?

**Comment by megabob1985** [comment]
Hi, 

Thank you for the response, but the funny thing is I was using it without Wi-Fi. So obviously it worked perfectly when I used it with Wi-Fi. Sorry for the trouble!

Thank you again,
Megabob1985

**Comment by Vegz78** [comment]
Great! Thanks for letting us know what the problem was!
